language: node_js
dist: trusty
sudo: required

addons:
  chrome: stable
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

install:
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

after_success: 'npm run coveralls'
